version: '3.4'

services:
    jaeger:
        container_name: "jaeger-container"
        ports:
        - "4317:4317"    #grpc
        - "4318:4318"    #http
        - "16686:16686"  #UI
    zipkin:
        container_name: "zipkin-container"
        ports:
        - "9411:9411"    #http
    redis:
        container_name: "redis-container"
        ports:
        - "6379:6379"    #redis
    rabbitmq:
        container_name: "rabbitmq-container"
        ports:
        - "5672:5672"    #amqp
        - "15672:15672"  #UI